### ISSUE TITLE
Selection of correct entry does not work

### ISSUE THREAD

**Issue by trondtynnol** [giellatekno/neahttadigisanit#10]
When searching for a word i language A and clicking the translation in language B, only the entry clicked should be shown, not all possible analyses of translation B. This has to my knowledge worked previously, at least restricting the result to the correct word class.

Some examples:
1) Search for "spraglet" in https://sanit.oahpa.no/nob/sme/ and click (the adjective) "girjái". Both the entry "girjái" (adj) and "girji" (noun) are shown, when only "girjái" should be. 
2) Search for "письмо" in https://sanj.oahpa.no/rus/sjd/ and click "кыррьй". The adjective "кыррьй" and the verb "кыррье" are shown before (!) the noun(s) "кыррьй".

The current situation may be very confusing for users who just want to find the conjugation table of the word they searched for.

**Comment by Phaqui** [comment]
Commit ac50f6bbe961acc07944113223e78daa40f83f69 copies over a filter that seemed unused. May fix the issue - at least the examples seems fixed.
