### ISSUE TITLE
config: strip_spaces - why?

### ISSUE THREAD

**Issue by Phaqui** [giellatekno/neahttadigisanit#21]
There is a setting called `strip_spaces` in project config files. It is boolean, and when it is `True`,
the search will run through a `.strip()` (stripping away whitespace at the beginning and end), before
it is passed on to lexical lookup and analysis. It is set to `True` in all templates, and all active configurations
which is live.

Why does this functionality exist - why doesn't the code just always `.strip()` the input?

**Comment by trondtynnol** [comment]
If I remember correctly, I implemented this on a user's suggestion, but wanted to make sure it did not break any other functionality, so I made it easily switchable. I guess the setting could be removed and the strip be done unconditionally now, as we have not seen any problems with the functionality.

**Comment by Phaqui** [comment]
Okay, sounds good. I was also hesitant to just remove it immediately, in case there was some use case I did not understand.
