### ISSUE TITLE
Autocomplete shows multiple result lists

### ISSUE THREAD

**Issue by trondtynnol** [giellatekno/neahttadigisanit#28]
Sometimes if I write quickly, especially if I delete a character and then write another, two lists of suggestions appear. 

In the following example I first typed "sama", then quickly deleted the a and wrote "sami" instead. As seen, the result is first the autocomplete for "sam" and then for "sami". When tabbing through this list, it jumps between the two. For the following picture, the tab moves as follows: samai > sami > samarianeǩ > sami pueʹrr > samasvetnai > sami šiõǥǥ > samasveâtnai and then continues down the upper list.
![image](https://github.com/giellatekno/neahttadigisanit/assets/55655546/5833d215-26ca-4577-b336-fe1ef8537f2f)

**Comment by Phaqui** [comment]
Fixed as of 10b30c6d315917acc813dd21352f3289f9ff449a

... At least I cannot reproduce it on the server anymore - maybe your fingers are faster than mine! :)

**Comment by trondtynnol** [comment]
Working for me too, I'm closing this as completed. :)
