### ISSUE TITLE
`fab sanit compile` does not update svn

### ISSUE THREAD

**Issue by Phaqui** [giellatekno/neahttadigisanit#3]
As title suggests. Quite possibly a regression introduced in 497c2699

For now, when dictionaries are updated, the temporary workaround is to manually enter the gtsvn dictionary and do `svn up` in there, before running `fab sanit compile` etc.

**Comment by Phaqui** [comment]
Untested fix live as of b96a01f8

**Comment by trondtynnol** [comment]
Tested `fab sanit compile` now, it works as it should on gtdict, fetching all svn files before compiling.
