### ISSUE TITLE
Search for čoma crashes sanat

### ISSUE THREAD

**Issue by trondtynnol** [giellatekno/neahttadigisanit#34]
Bug report from a user: [A search for čoma](https://sanat.oahpa.no/vep/fin/?lookup=%C4%8Doma&search=) in the vep-fin dictionary in sanat causes a 500 crash.

**Comment by Phaqui** [comment]
Fixed the crash in 0ffc01584469a336c8811b38acbcdb8c68061358. Does the search results look correct now?
