### ISSUE TITLE
Paradigme fungerer ikke på mobil

### ISSUE THREAD

**Issue by Phaqui** [giellatekno/neahttadigisanit#4]
Fikk en ei brukermelding om at paradigme ikke fungerer i det hele tatt på mobil.

Har ikke fått til å reprodusere feilen, og det kan være vanskelig, da det kan være så mangt, deriblandt spesifikk browser eller versjon av browser på brukerens telefon, evt addons installert, og selvfølgelig kan det hende at det kun skjer med enkelte ord eller uttrykk.

**Comment by trondtynnol** [comment]
Til info hadde brukaren ein iPhone og brukte Safari som nettlesar. Eg har ikkje klart å reprodusere dette i Safari på iPhone sjølv.

**Comment by Phaqui** [comment]
En feil som oppsto etter at jeg endret til esbuild, og byggerutinine av javascript, var at koden ble bundlet to ganger, slik at f.eks event handleren som toggler paradigmetabellen ble inkludert to ganger, slik at når man klikket på knappen, så ble tabellen "togglet" to ganger, og man oppnådde effekten at den bare raskt lukket seg igjen med en gang.

Men, denne byggingsfeilen har blitt rettet opp, og var nok ikke det som ble rapportert om her.
