### ISSUE TITLE
Feil rekkefølge på søkeresultater

### ISSUE THREAD

**Issue by Phaqui** [giellatekno/neahttadigisanit#5]
eks: på søkeordet "viessu", skal "viessu" komme før "viessat", fordi det er direkte treff på lemma.

**Comment by Phaqui** [comment]
Lokalt er rekkefølgen akkurat slik vi vil ha den.

**Comment by Phaqui** [comment]
Som ei midlertidig løsning endra jeg tilbake til "hfst" i `configs/sanit.config.yaml:55` (og den for "SoMe"). Rekkefølgen er nå riktig, men man merker faktisk at oppslag tar noe lengre tid.

**Comment by trondtynnol** [comment]
Aha, så vi har vore avhengige av kva rekkjefylgje hfst returnerer lemma i. Det er vel i grunn ikkje noko å stole på. Godt du fann årsaka, Anders.

**Comment by Phaqui** [comment]
Da skal denne være fikset fra og med commit 648466df. Lar issuet stå åpent inntill vi får testet skikkelig.

Det viste seg å være marginale forskjeller i newlines fra outputet generert av "PyHFST" og "HFST", som gjorde at resultatene til "PyHFST" ikke kom "i samme pulje" (det var to mellomrom mellom hvert treff fra analysatoren).

Noe (jeg aner ikke hva - selv etter noen timers utforskning..), tar denne outputen, og ordner rekkefølgen slik at den blir riktig. Nå som outputtet fra PyHFST er lik HFST, så blir resultatene også ordnet på riktig måte.

**Comment by Phaqui** [comment]
Ser ut til at fiksen har fungert, da vi ikke har registrert noen flere tilfeller. Vi får heller gjenåpne hvis det kommer tilbake!
